### ISSUE TITLE
Consider changing license from AGPL to a more permissive license

### ISSUE THREAD

**Issue by jabinb** [jbreckmckye/robot3-viz#1]
Hi there, first of all this is a great library, thank you for spending the time making it!

I'd really love to use this for visualizing state trees used in our robot3 react components. However being licensed AGPL essentially means any code that uses  `robot3-viz` should be also be open sourced. For example if we `npm install`'d this in our backend it would mean we would legally be required to open-source our entire backend code, which is obviously a blocker.

I'm not sure what the intentions are of the library, whether you intend only for this to be used in other open-source projects, but this heavily impairs people from adopting this library, especially considering this is mostly an optional visualization tool (though a very useful one).

You can find more in-depth overview and discussion from when `react-page` went through re-licensing to LGPL from AGPL here:
https://github.com/react-page/react-page/issues/

If possible it could you change the license to something more permissive like Apache, BSD, or MIT?

**Comment by jbreckmckye** [comment]
Hi Jabin, can you tell me a little more about your use-case?

My intention with the license was this: it's fine to use the visualiser as an internal _developer_ tool in any project, including commercial ones, but you cannot "repackage" or use it as a dependency of your production software, without either a) that software being open sourced or b) requesting a license

So if your goal is just to use robot3-viz as a developer tool, for internal use, e.g. to generate developer documentation, that's completely okay.

On the other hand, if you want to create a webservice that serves the visualisations for users, that's a different matter.

The key term is "covered work". Are you selling a program that lets people visualise their robot3 state machines? That's a covered work. Are you just creating PNGs privately to visualise your state machines? Then your backend isn't a covered work because it doesn't wrap or modify this library

**Comment by jabinb** [comment]
For us the use-case would be the former, just for use in developer documentation, more specifically to be used inside Storybooks alongside the UI controls as visual documentation. For context our product is for retail stock investors, so nothing to do with visualizing state trees.

I've read up a bit on AGPL so I understand the distinction you're making between what's considered covered and not covered use. As I understand it our potential use case would be not be in violation, however in most organizations using AGPL licensed libraries is quite contentious as there's an uncertainty about the legal requirements if the library were to be linked into production code by mistake, e.g. `robot3-viz` was put into `dependencies` rather than `devDependencies` and shipped to users (as a contrived example).

Whilst I believe it's OK even in that example (as long as the code is not modified) its unfortunately not how other people see it. Basically it boils down to AGPL (used in any form) being perceived as a headache and a legal risk to management due to things like [Google's AGPL policy](https://opensource.google/documentation/reference/using/agpl-policy) and [other concerns expressed online](https://news.ycombinator.com/item?id=31176071). The development team is asked to justify spending legal resources with questions like "Do we really need this thing?" and unfortunately after a wringing of hands the answer is "Not really..." and so any AGPL licensed project is deemed untenable. In our scenario it's also a cause for concern during external audits, i.e. as technical due diligence as part of a funding round, which ratchets up the risk higher.

The situation overall sucks as AGPL is about stopping bad actors from taking OSS code and profiting off of it, which I strongly agree with, and not for shadowing projects in legal uncertainty like it's reputation has given it. To give my unsolicited opinions here... I'm skeptical there's any threat at all of someone wrapping this library up and selling it, it would be more likely to happen to say `robot3` itself (which is BSD-2). So AGPLs unfortunate stigma unnecessarily restricts the use of `robot3-viz` from helping 99% of dev teams who work on commercial products. 

That said I completely understand if you disagree, and or just don't have any interest in changing licenses and respect your decision if that's the case.

**Comment by jbreckmckye** [comment]
Yeah, I understand the problem.

I'll have to think about it. I'm not necessarily too worried about the risk of this project being absorbed into a commercial tool - it's not a big complex piece of code, it's pretty niche. So something like MIT might be worth it to promote re-use.

For other projects, though, I'm not so sure. Over the last twelve months I've seen a lot of VC funded startups muscling into the JavaScript tooling space. Quite a few of these have cherry picked MIT licensed software into their own commercial products.

Given that your organisation performs audits on its dependencies, may I ask how many MIT licensed projects you are using? And may I also ask how many of those projects your organisation has contributed back to?

**Comment by jbreckmckye** [comment]
Yeah, I understand the problem.

This is a fairly niche library and I'm not massively worried about it being used in a commercial project. And ultimately I would rather this software be used, than unused.

I will have a think about it overnight.

Here's a question, though: given your org uses exclusively MIT / BSD / permissive licensed dependencies - what kinds of contributions does it provide back?

**Comment by jbreckmckye** [comment]
After reflecting on it I've decided to move to a BSD 2-clause license because

1. It's the same license as Robot itself
2. There's not enough proprietary code in this package for me to need to 'protect' from commercial interests
3. Ultimately, I'd rather this library be used, than not used

As such I've released a new version 1.0.3 which contains the new license.

**Comment by jabinb** [comment]
>Here's a question, though: given your org uses exclusively MIT / BSD / permissive licensed dependencies - what kinds of contributions does it provide back?

Sure happy to answer but with the caveat that our org is not very representative of the average case -- we're a small startup with only 2 engineers (me being one of them) so our resources are spread quite thin. However we do have internally have a policy of upstreaming any fixes or improvements we make to libraries we use. So far our contributions have been to [@no-day/fp-ts-graph](https://github.com/no-day/fp-ts-graph) which we do use as a core part of some of our systems.

> After reflecting on it I've decided to move to a BSD 2-clause license because
> 
>     1. It's the same license as Robot itself
> 
>     2. There's not enough proprietary code in this package for me to need to 'protect' from commercial interests
> 
>     3. Ultimately, I'd rather this library be used, than not used
> 
> 
> As such I've released a new version 1.0.3 which contains the new license.

Thank you! This is very gracious of you, I'll close this issue now.

If we come up with anything that can be contributed I'll be sure to send a PR, or otherwise let me know if there's anything useful I can do, I'd be happy to contribute directly to the project as well.
