### ISSUE TITLE
v1.0.3 bad npm publish?

### ISSUE THREAD

**Issue by jabinb** [jbreckmckye/robot3-viz#2]
Comparing v1.0.2 to v1.0.3 it looks like only the `index.js` file got published to the `dist` folder, the rest is missing?

Can see here on unpkg:
https://unpkg.com/browse/robot3-viz@1.0.3/dist/ 

Compared to:
https://unpkg.com/browse/robot3-viz@1.0.2/dist/

**Comment by jbreckmckye** [comment]
Thanks for the notification. Looks like something has gone wrong; will publish a v1.0.4

**Comment by jbreckmckye** [comment]
Have published v1.0.4
